### ISSUE TITLE
training of PCR fragments

### ISSUE THREAD

**Issue by lfaino** [nanoporetech/bonito#118]
Dear developers,
I have a question. I`m trying to improve basecalling of a two PCR fragments. So I generated my database with the 2 fragments and I have about 8000 reads for both sequences. I run Bonito basecaller and after the training step but when I call the data back I get that each sequence has only one base.

can you please help?

cheers
Luigi

**Comment by iiSeymour** [comment]
Hey @lfaino 

Are you saying you basecalled 16,000 reads _(2x 8,000)_ with `--save-ctc` and then trained a new model from scratch? If so, how many chunks did you end up with? Can you share the `training.csv` output? 16,000 reads is on the low side for training a new model. It might be better to try finetuning the release model with your data rather than training a new model from scratch.

**Comment by lfaino** [comment]
I agree.

how can i do this? where can i find the instruction to make a finetuning?
cheers

[training.txt](https://github.com/nanoporetech/bonito/files/5964641/training.txt)

**Comment by iiSeymour** [comment]
Assuming this is `dna_r9.4.1 ` then try:

```
bonito train --epochs 1 --lr 5e-4 --pretrained dna_r9.4.1 --directory pcr-frag-training-data finetuned-model
```

**Comment by lfaino** [comment]
ok thanks it worked
