### ISSUE TITLE
Bonito download --models not downloading all models>

### ISSUE THREAD

**Issue by clock-matt** [nanoporetech/bonito#313]
I'm using bonito 0.6.1 and when I use bonito download --models it only downloads:
 - dna_r10.4.1_e8.2_260bps_fast@v3.5.2
 - dna_r10.4.1_e8.2_260bps_hac@v3.5.2
 - dna_r10.4.1_e8.2_260bps_sup@v3.5.2
 - dna_r10.4.1_e8.2_400bps_fast@v3.5.2
 - dna_r10.4.1_e8.2_400bps_hac@v3.5.2
 - dna_r10.4.1_e8.2_400bps_sup@v3.5.2
 - dna_r9.4.1_e8_sup@v3.3
 - dna_r9.4.1_e8_hac@v3.3
 - dna_r9.4.1_e8_fast@v3.4
 
I need 
dna_r10.4.1_e8.2_sup@v3.5.2

Because of this error: 
remora.RemoraError: No trained Remora models for dna_r10.4.1_e8.2_400bps. Options: dna_r9.4.1_e8, dna_r9.4.1_e8.1, dna_r10.4_e8.1, dna_r10.4.1_e8.2

I'm not sure if I'm doing something wrong, or if there is some way to download this bonito model, or if there is a different remora model I can use with the bonito models I have available

**Comment by yusmiatiliau** [comment]
Hi, I got the exact same issue. Is there a solution for this yet?

so I run: 
bonito basecaller dna_r10.4.1_e8.2_400bps_sup@v3.5.2 /path/fast5_pass/ --modified-bases 5mC --reference /path/ REF.mmi --modified-base-model /path/5mC_all_context_sup_r1041_e82.onnx > output.bam

and it gave me this error:
remora.RemoraError: No trained Remora models for dna_r10.4.1_e8.2_400bps. Options: dna_r9.4.1_e8, dna_r9.4.1_e8.1, dna_r10.4_e8.1, dna_r10.4.1_e8.2

I have downloaded all the models, and confirm they are in bonito/models/

When I tried without the rerio model (so without the --modified-base-model, I still get the same error.

Thanks

**Comment by marcus1487** [comment]
The `--modified-bases` and `--modified-base-model` options should be exclusive. We will look at enforcing this in bonito. If you remove the `--modified-bases` option this command should work.

The other issue here is the condition name change update. Bonito changed the name of the condition from `dna_r10.4.1_e8.2` to `dna_r10.4.1_e8.2_400bps` in the 3.5.2 model release. Remora has not had a release since then, but the next release coming in the next week will rectify this naming difference. As a workaround remora models are currently found in the repository [here](https://github.com/nanoporetech/remora/tree/master/src/remora/trained_models). So you can find the appropriate remora model and provided it via the `--modified-base-model` argument. In the next release of remora though the models will no longer be shipped with remora and will have to be downloaded. They will be downloaded to this same location in the repo though.

**Comment by yusmiatiliau** [comment]
Hi @marcus1487,
Thanks for this. I removed --modified-bases 5mC, and bonito is up and running now
