### ISSUE TITLE
Keyerror : block

### ISSUE THREAD

**Issue by joscarhuguet** [nanoporetech/bonito#33]
hello
I am trying to run bonito
bonito basecaller --fastq dna_r9.4.1 1/ > fastq
But got an error form python
 
Traceback (most recent call last):
  File "/apps/ont-bonito/0.1.5/bin/bonito", line 11, in <module>
    load_entry_point('ont-bonito==0.1.5', 'console_scripts', 'bonito')()
  File "/apps/ont-bonito/0.1.5/lib/python3.8/site-packages/ont_bonito-0.1.5-py3.8.egg/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/apps/ont-bonito/0.1.5/lib/python3.8/site-packages/ont_bonito-0.1.5-py3.8.egg/bonito/basecaller.py", line 19, in main
    model = load_model(args.model_directory, args.device, weights=int(args.weights), half=args.half)
  File "/apps/ont-bonito/0.1.5/lib/python3.8/site-packages/ont_bonito-0.1.5-py3.8.egg/bonito/util.py", line 202, in load_model
    model = Model(toml.load(config))
  File "/apps/ont-bonito/0.1.5/lib/python3.8/site-packages/ont_bonito-0.1.5-py3.8.egg/bonito/model.py", line 44, in __init__
    self.stride = config['block'][0]['stride'][0]
KeyError: 'block

**Comment by iiSeymour** [comment]
Hello @joscarhuguet 

Did you install Bonito with pip or clone from GitHub?

**Comment by joscarhuguet** [comment]
I used
sudo pip install ont-bonito

**Comment by iiSeymour** [comment]
Can you confirm the installation has the model directory containing an unmodified config and weight file as per below?

```bash
$ ls /apps/ont-bonito/0.1.5/lib/python3.8/site-packages/ont_bonito-0.1.5-py3.8.egg/bonito/models/dna_r9.4.1/
config.toml  weights_1.tar
$ md5sum /apps/ont-bonito/0.1.5/lib/python3.8/site-packages/ont_bonito-0.1.5-py3.8.egg/bonito/models/dna_r9.4.1/
6651b1672497cc99674fd55957db7509  config.toml
3790d2c732af616c8d17cad8f877b0df  weights_1.tar
```

And please upload the `config.toml` if the hash doesn't match.

**Comment by max1c** [comment]
Hi @iiSeymour 

It was actually installed with conda.

$ md5sum /apps/ont-bonito/0.1.5/lib/python3.8/site-packages/ont_bonito-0.1.5-py3.8.egg/bonito/models/dna_r9.4.1/config.toml
647b6dbe14791431a37f645771389102 

Here is the config.toml renamed to .txt to upload. 
[config.txt](https://github.com/nanoporetech/bonito/files/4612377/config.txt)

**Comment by iiSeymour** [comment]
Okay, so the traceback isn't lying! The config doesn't contain the model description at all - [see here](https://github.com/nanoporetech/bonito/blob/master/bonito/models/configs/quartznet5x5.toml).

Can you confirm the source location the package is coming from? If it's not https://pypi.org/project/ont-bonito/ then I can only guess somebody is distributing the package incorrectly on conda.

Running `bonito download --models` will probably resolve the issue but it would be good to get to the bottom of the root cause.

**Comment by max1c** [comment]
This is what I get:
$ bonito download --models
[downloading models]
[skipping dna_r9.4.1.zip]

It looks like conda downloads it from pypi:
ont-bonito                0.1.5                    pypi_0    pypi

**Comment by iiSeymour** [comment]
The download skips because you already have a `dna_r9.4.1` directory. Does the directory only contain the modified `config.toml` or does it also have a `weights_1.tar`? If you remove the `dna_r9.4.1` the download won't skip.

I really can't see how you would end up with a config like that - see the raw package files on PyPI https://pypi.org/project/ont-bonito/#files

```bash
$ wget https://files.pythonhosted.org/packages/95/fa/8a178168ee44c7f66a4239e4a2a1569896e787397080d1e1e0c2b1a331c2/ont-bonito-0.1.5.tar.gz
$ tar xzf ont-bonito-0.1.5.tar.gz
$ md5 ont-bonito-0.1.5/bonito/models/dna_r9.4.1/config.toml
MD5 (ont-bonito-0.1.5/bonito/models/dna_r9.4.1/config.toml) = 6651b1672497cc99674fd55957db7509
$ md5 ont-bonito-0.1.5/bonito/models/dna_r9.4.1/weights_1.tar
MD5 (ont-bonito-0.1.5/bonito/models/dna_r9.4.1/weights_1.tar) = 3790d2c732af616c8d17cad8f877b0df
```

Can you try uninstalling the package and reinstalling it.

**Comment by max1c** [comment]
Ok, after re-installing the package from your link it has the correct files:

$ md5sum config.toml
6651b1672497cc99674fd55957db7509  config.toml
$ md5sum weights_1.tar
3790d2c732af616c8d17cad8f877b0df  weights_1.tar
