### ISSUE TITLE
Bonito bascaller issue

### ISSUE THREAD

**Issue by AntFch** [nanoporetech/bonito#337]
Hi,

I'm currently working on HHV8 methylation. So I want to use a remora model in bonito basecaller. I downloaded all remora models and then I launched this command:

`bonito basecaller dna_r9.4.1_e8_sup@v3.3 test_methyl/ --modified-bases 5mc --reference Ref_seq/HHV8_ref.mmi > test_methyl/test_barcode01.bam`

which testmethyl contains just one FAST5 file, and Ref_seq the HHV8 indexed sequence with minimap2.

However I get an error with the dowloading model part:

> > downloading model
> Traceback (most recent call last):
>   File "/home/grid/miniconda3/envs/methyl/bin/bonito", line 8, in <module>
>     sys.exit(main())
>   File "/home/grid/miniconda3/envs/methyl/lib/python3.10/site-packages/bonito/__init__.py", line 34, in main
>     args.func(args)
>   File "/home/grid/miniconda3/envs/methyl/lib/python3.10/site-packages/bonito/cli/basecaller.py", line 47, in main
>     File(__models__, models[args.model_directory]).download()
> TypeError: list indices must be integers or slices, not str

I don't understand why I get this. Can you help me to resolve it ?

Best regards,
Antoine.

**Comment by jgustavsen** [comment]
Hi, I am receiving the same error. Anything that we can try?

**Comment by chAwater** [comment]
@iiSeymour I think this is a bug caused by 
https://github.com/nanoporetech/bonito/commit/f2f1a7ecc416c2f21682803c8f4f950bab0a45a9 which changes the `models` from dict to list
https://github.com/nanoporetech/bonito/blob/3bc338a0b289d46b2f2b3330f0c37de89a7853f9/bonito/cli/download.py#L80-L83 to 
https://github.com/nanoporetech/bonito/blob/f2f1a7ecc416c2f21682803c8f4f950bab0a45a9/bonito/cli/download.py#L80-L83

That causes an error when you don't have the model and trigger the download in `basecaller`
https://github.com/nanoporetech/bonito/blob/655feea4bca17feb77957c7f8be5077502292bcf/bonito/cli/basecaller.py#L45-L47

@AntFch @jgustavsen That's why the `bonito download --models`, which downloads all the available models, will "solve" it.
