### ISSUE TITLE
Resuming a run

### ISSUE THREAD

**Issue by chocotwig** [nanoporetech/bonito#34]
Hi,

I am wondering -- if bonito terminates for whatsoever reason during a run, is there a way to restart the run and pick up from where it left off?

Thanks!

**Comment by iiSeymour** [comment]
I can think of a couple of ways to do this - but perhaps the providing a `--skip` flag that takes a file containing read_ids would be best? Then you could either use a new output file with `>` or append to the prior one with `>>`.  

```
$ bonito basecaller  --half --skip read_ids dna_r9.4.1 reads >> call.fasta 
```

Does that work for you?

**Comment by cdebuck** [comment]
Hi,

I am using bonito version 0.5.1 and I'm also interested in restarting a run, and supplying read-ids that bonito can skip. I looked into the --skip argument, but I cannot use it in the way that is described above, because I cannot supply a file with read_ids to the --skip argument.
Is this a bug, or am I misunderstanding the use of the --skip argument?
