### ISSUE TITLE
data conversion error

### ISSUE THREAD

**Issue by aCoalBall** [nanoporetech/bonito#355]
Hi there,

I have successfully downloaded the training data using

`bonito download --training`

But I meet errors when converting it:

`bonito convert dna_r9.4.1.hdf5 dna_r9.4.1`

`File "mtrand.pyx", line 4703, in numpy.random.mtrand.RandomState.permutation
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (66149, 2) + inhomogeneous part.`

Is there any way to fix it?

**Comment by chAwater** [comment]
Hi @aCoalBall, Could you please show your numpy version? 

- This error is also shown in #347 
- I guess your numpy version is >= 1.24.0, which raise `ValueError` instead of `DeprecationWarning` [(release note)](https://github.com/numpy/numpy/blob/dabb12ec5c27846b1ded065b5e61eabb89d029ed/doc/source/release/1.24.0-notes.rst#expired-deprecations).
- If that is true, this PR might fix this error: #311

**Comment by aCoalBall** [comment]
Thanks, you are right! my numpy is 1.24.2 and I have fixed the error.
