### ISSUE TITLE
how to calibrate CTC-CRF model base qualities?

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/bonito#375]
Hi, how to calibrate bonito trained models so base qualities correspond to expected error rate? 
For example `config.toml` for RNA004 sup models uses: 

```bash
[qscore]
scale = 0.9
bias = -0.1
```

How were those values obtained?

**Comment by lpryszcz** [comment]
any update on this? we're in [the review process of basecalling model trained with bonito](https://www.biorxiv.org/content/10.1101/2023.11.28.568965v1.full.pdf) and we are unable to calibrate qscores therefore qscores from CTC-CRF models are not comparable with older models (flip-flop). 
I have opened similar issue in [dorado repo](https://github.com/nanoporetech/dorado/issues/576)

**Comment by yinshiyi** [comment]
I see your paper is accepted
https://pubmed.ncbi.nlm.nih.gov/39271295/
Congrats, did you figure it out at the end? Thanks

**Comment by lpryszcz** [comment]
thanks, unfortunately no.

**Comment by davidnewman02** [comment]
The q-score calibrations for each model are calibrated using a large pool of diverse data and adjusting the parameters such that the q-score distribution and accuracy distribution match approximately.

Thanks for sharing the link to your paper which is an interesting approach to detecting m6A methylation in RNA. 
Recent models for RNA004 have made significant improvements in basecalling RNA data and we now provide an explicit m6A methylation caller in Dorado: https://dorado-docs.readthedocs.io/en/latest/basecaller/mods/#rna-modifications I would be interested to know whether this would help your application.

**Comment by lpryszcz** [comment]
dear @davidnewman02 , the problem is that as far as I'm aware, no one outside of ONT is able to calibrate CTC-CRF models trained with bonito. could you please provide a methodology you are using? such information was disclosed for [taiyaki](https://github.com/nanoporetech/taiyaki/?tab=readme-ov-file#q-score-calibration).

**Comment by davidnewman02** [comment]
The process is not significantly different to how it worked in Taiyaki. Calibration can be performed with any sample of basecalls that you have available with a reference, the approximate process is as follows:

1. Basecall a dataset with the calibration set to `scale=1, bias=0`
2. Compare the `alignment_accuracy` (in q-space) to the `mean_qscore`
3. Pick an appropriate `scale` and `bias` so that the distributions approximately match
4. Basecall a test dataset with the new calibration to check it is appropriate

Remember to be careful when applying the scale and shift in log vs. linear space and when aggregating the q-scores across the read, but this can easily be accounted for when doing your fitting.
