### ISSUE TITLE
Download/installation errors

### ISSUE THREAD

**Issue by peadams** [nanoporetech/bonito#74]
Hello, when I pip install bonito it fails to build the wheel, and then installs using the legacy 'setup.py install' method. But it says it was successfully installed. 

"DEPRECATION: ont-bonito was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368."

however, when I call bonito i get this error: 
pkg_resources.DistributionNotFound: The 'ont-bonito==0.3.1' distribution was not found and is required by the application

So somewhere it is not installing correctly. 

I am using python version 3.8.6 and pip version 20.2.4. I was able to successfully install other software to double check that my python appears to be working.

I have also tried to install by downloading the tar package manually, and got similar results.  

Full error added Dec. 1st, 2020

```
sudo pip3 --no-cache-dir install ont-bonito
Collecting ont-bonito
  Downloading ont-bonito-0.3.1.tar.gz (35 kB)
Requirement already satisfied: mappy==2.17 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (2.17)
Requirement already satisfied: toml==0.10.0 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (0.10.0)
Requirement already satisfied: tqdm==4.31.1 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (4.31.1)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Requirement already satisfied: torch<=1.5,>=1.1.0 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.5.0)
Requirement already satisfied: optuna==1.1.0 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.1.0)
Requirement already satisfied: parasail==1.2 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.2)
Requirement already satisfied: seqdist==0.0.1 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (0.0.1)
Requirement already satisfied: requests==2.22.0 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (2.22.0)
Requirement already satisfied: crf-beam==0.0.1a0 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (0.0.1a0)
Requirement already satisfied: ont-fast5-api==3.1.6 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (3.1.6)
Requirement already satisfied: fast-ctc-decode==0.2.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (0.2.5)
Requirement already satisfied: Cython>=0.25.2 in /usr/local/lib/python3.8/site-packages (from crf-beam==0.0.1a0->ont-bonito) (0.29.21)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Requirement already satisfied: progressbar33>=2.3.1 in /usr/local/lib/python3.8/site-packages (from ont-fast5-api==3.1.6->ont-bonito) (2.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/site-packages (from ont-fast5-api==3.1.6->ont-bonito) (20.4)
Requirement already satisfied: h5py>=2.6 in /usr/local/lib/python3.8/site-packages (from ont-fast5-api==3.1.6->ont-bonito) (3.1.0)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Requirement already satisfied: alembic in /usr/local/lib/python3.8/site-packages (from optuna==1.1.0->ont-bonito) (1.4.3)
Requirement already satisfied: cliff in /usr/local/lib/python3.8/site-packages (from optuna==1.1.0->ont-bonito) (3.5.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.8/site-packages (from optuna==1.1.0->ont-bonito) (4.6.2)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Requirement already satisfied: scipy!=1.4.0 in /usr/local/lib/python3.8/site-packages (from optuna==1.1.0->ont-bonito) (1.5.4)
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/local/lib/python3.8/site-packages (from optuna==1.1.0->ont-bonito) (1.3.20)
Requirement already satisfied: tqdm==4.31.1 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (4.31.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/site-packages (from optuna==1.1.0->ont-bonito) (0.17.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.8/site-packages (from alembic->optuna==1.1.0->ont-bonito) (1.1.3)
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/local/lib/python3.8/site-packages (from optuna==1.1.0->ont-bonito) (1.3.20)
Requirement already satisfied: python-editor>=0.3 in /usr/local/lib/python3.8/site-packages (from alembic->optuna==1.1.0->ont-bonito) (1.0.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/site-packages (from alembic->optuna==1.1.0->ont-bonito) (2.8.1)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (1.15.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (5.5.1)
Requirement already satisfied: stevedore>=2.0.1 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (3.2.2)
Requirement already satisfied: PrettyTable<0.8,>=0.7.2 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (0.7.2)
Requirement already satisfied: pyparsing>=2.1.0 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (2.4.7)
Requirement already satisfied: cmd2!=0.8.3,>=0.8.0 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (1.4.0)
Requirement already satisfied: PyYAML>=3.12 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (5.3.1)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python3.8/site-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna==1.1.0->ont-bonito) (0.2.5)
Requirement already satisfied: pyperclip>=1.6 in /usr/local/lib/python3.8/site-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna==1.1.0->ont-bonito) (1.8.1)
Requirement already satisfied: attrs>=16.3.0 in /usr/local/lib/python3.8/site-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna==1.1.0->ont-bonito) (20.3.0)
Requirement already satisfied: colorama>=0.3.7 in /usr/local/lib/python3.8/site-packages (from cmd2!=0.8.3,>=0.8.0->cliff->optuna==1.1.0->ont-bonito) (0.4.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.8/site-packages (from Mako->alembic->optuna==1.1.0->ont-bonito) (1.1.1)
Requirement already satisfied: pyparsing>=2.1.0 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (2.4.7)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (1.15.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.8/site-packages (from parasail==1.2->ont-bonito) (0.35.1)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (1.15.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests==2.22.0->ont-bonito) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests==2.22.0->ont-bonito) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests==2.22.0->ont-bonito) (2020.11.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests==2.22.0->ont-bonito) (1.25.11)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Requirement already satisfied: cupy-cuda102 in /usr/local/lib/python3.8/site-packages (from seqdist==0.0.1->ont-bonito) (8.2.0)
Requirement already satisfied: torch<=1.5,>=1.1.0 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.5.0)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Requirement already satisfied: fastrlock>=0.3 in /usr/local/lib/python3.8/site-packages (from cupy-cuda102->seqdist==0.0.1->ont-bonito) (0.5)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python3.8/site-packages (from cliff->optuna==1.1.0->ont-bonito) (5.5.1)
Requirement already satisfied: future in /usr/local/lib/python3.8/site-packages (from torch<=1.5,>=1.1.0->ont-bonito) (0.18.2)
Requirement already satisfied: numpy<=1.18.5 in /usr/local/lib/python3.8/site-packages (from ont-bonito) (1.18.5)
Building wheels for collected packages: ont-bonito
  Building wheel for ont-bonito (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ah5l1uls/ont-bonito_8374830f39f84c728a984a16376848fe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ah5l1uls/ont-bonito_8374830f39f84c728a984a16376848fe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-o4lx8eya
       cwd: /tmp/pip-install-ah5l1uls/ont-bonito_8374830f39f84c728a984a16376848fe/
  Complete output (93 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/bonito
  copying bonito/fast5.py -> build/lib/bonito
  copying bonito/util.py -> build/lib/bonito
  copying bonito/multiprocessing.py -> build/lib/bonito
  copying bonito/nn.py -> build/lib/bonito
  copying bonito/io.py -> build/lib/bonito
  copying bonito/training.py -> build/lib/bonito
  copying bonito/__init__.py -> build/lib/bonito
  copying bonito/aligner.py -> build/lib/bonito
  creating build/lib/bonito/ctc
  copying bonito/ctc/model.py -> build/lib/bonito/ctc
  copying bonito/ctc/__init__.py -> build/lib/bonito/ctc
  copying bonito/ctc/basecall.py -> build/lib/bonito/ctc
  creating build/lib/bonito/cli
  copying bonito/cli/tune.py -> build/lib/bonito/cli
  copying bonito/cli/basecaller.py -> build/lib/bonito/cli
  copying bonito/cli/convert.py -> build/lib/bonito/cli
  copying bonito/cli/train.py -> build/lib/bonito/cli
  copying bonito/cli/view.py -> build/lib/bonito/cli
  copying bonito/cli/pair.py -> build/lib/bonito/cli
  copying bonito/cli/__init__.py -> build/lib/bonito/cli
  copying bonito/cli/evaluate.py -> build/lib/bonito/cli
  copying bonito/cli/download.py -> build/lib/bonito/cli
  creating build/lib/bonito/crf
  copying bonito/crf/model.py -> build/lib/bonito/crf
  copying bonito/crf/__init__.py -> build/lib/bonito/crf
  copying bonito/crf/basecall.py -> build/lib/bonito/crf
  running egg_info
  writing ont_bonito.egg-info/PKG-INFO
  writing dependency_links to ont_bonito.egg-info/dependency_links.txt
  writing entry points to ont_bonito.egg-info/entry_points.txt
  writing requirements to ont_bonito.egg-info/requires.txt
  writing top-level names to ont_bonito.egg-info/top_level.txt
  reading manifest file 'ont_bonito.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'ont_bonito.egg-info/SOURCES.txt'
  creating build/lib/bonito/data
  copying bonito/data/README.md -> build/lib/bonito/data
  creating build/lib/bonito/models
  copying bonito/models/README.md -> build/lib/bonito/models
  creating build/lib/bonito/models/configs
  copying bonito/models/configs/dna_r9.4.1@v1.toml -> build/lib/bonito/models/configs
  copying bonito/models/configs/dna_r9.4.1@v2.toml -> build/lib/bonito/models/configs
  copying bonito/models/configs/dna_r9.4.1@v3.toml -> build/lib/bonito/models/configs
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/bonito
  creating build/bdist.linux-x86_64/wheel/bonito/ctc
  copying build/lib/bonito/ctc/model.py -> build/bdist.linux-x86_64/wheel/bonito/ctc
  copying build/lib/bonito/ctc/__init__.py -> build/bdist.linux-x86_64/wheel/bonito/ctc
  copying build/lib/bonito/ctc/basecall.py -> build/bdist.linux-x86_64/wheel/bonito/ctc
  creating build/bdist.linux-x86_64/wheel/bonito/models
  creating build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/configs/dna_r9.4.1@v3.toml -> build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/configs/dna_r9.4.1@v1.toml -> build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/configs/dna_r9.4.1@v2.toml -> build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/README.md -> build/bdist.linux-x86_64/wheel/bonito/models
  copying build/lib/bonito/fast5.py -> build/bdist.linux-x86_64/wheel/bonito
  creating build/bdist.linux-x86_64/wheel/bonito/data
  copying build/lib/bonito/data/README.md -> build/bdist.linux-x86_64/wheel/bonito/data
  copying build/lib/bonito/util.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/multiprocessing.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/nn.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/io.py -> build/bdist.linux-x86_64/wheel/bonito
  creating build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/tune.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/basecaller.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/convert.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/train.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/view.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/pair.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/__init__.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/evaluate.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/download.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  creating build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/crf/model.py -> build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/crf/__init__.py -> build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/crf/basecall.py -> build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/training.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/__init__.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/aligner.py -> build/bdist.linux-x86_64/wheel/bonito
  running install_egg_info
  Copying ont_bonito.egg-info to build/bdist.linux-x86_64/wheel/ont_bonito-0.3.1-py3.8.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'bonito'
  ----------------------------------------
  ERROR: Failed building wheel for ont-bonito
  Running setup.py clean for ont-bonito
Failed to build ont-bonito
Installing collected packages: ont-bonito
    Running setup.py install for ont-bonito ... done
  DEPRECATION: ont-bonito was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
```

**Comment by peadams** [comment]
I think mine is actually the same as #71 but I don't know how to fix it? It fails to build the wheel with the last line of error being "No such file or directory: "bonito" followed by "Failed building wheel for ont-bonito". Then installs using "setup.py install."


That install of bonito does not work because CuPy is not working without the wheel. I'm now working on the CuPy issue, but re-installing CuPy just makes bonito think it is not there.


CuPy error after calling bonito basecaller /reads > basecalled.fasta 

> loading model
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cupy/__init__.py", line 20, in <module>
    from cupy import core  # NOQA
  File "/usr/local/lib/python3.8/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito==0.3.1', 'console_scripts', 'bonito')())
  File "/usr/local/lib/python3.8/site-packages/bonito/__init__.py", line 39, in main
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/bonito/cli/basecaller.py", line 26, in main
    model = load_model(args.model_directory, args.device, weights=int(args.weights))
  File "/usr/local/lib/python3.8/site-packages/bonito/util.py", line 283, in load_model
    Model = load_symbol(config, "Model")
  File "/usr/local/lib/python3.8/site-packages/bonito/util.py", line 250, in load_symbol
    imported = import_module(config['model']['package'])
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/bonito/crf/__init__.py", line 1, in <module>
    from .model import Model
  File "/usr/local/lib/python3.8/site-packages/bonito/crf/model.py", line 10, in <module>
    import seqdist.sparse
  File "/usr/local/lib/python3.8/site-packages/seqdist/sparse.py", line 9, in <module>
    import cupy as cp
  File "/usr/local/lib/python3.8/site-packages/cupy/__init__.py", line 41, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: libcublas.so.10: cannot open shared object file: No such file or directory

**Comment by hermannschwaerzlerUIBK** [comment]
Dear @peadams,

no idea if this is of any help but we were able to get a working bonito (despite the wheel-installation problem) by using conda to install an environment containing python (3.8.6), pip (20.3), pytorch (1.5.0), cudatoolkit (10.2.89) and others; after activating this environment we installed bonito via pip (ignoring the wheel installation error):
```
conda create -n bonito python pip pytorch=1.5.0 torchvision cudatoolkit 'numpy<=1.18.5' -c pytorch -c conda-forge

conda activate bonito
pip install ont-bonito
```
Now we are able to successfully basecall (on a system having GPUs installed) using
```
conda activate bonito
bonito basecaller --device cuda ...
```

**Comment by aspitaleri** [comment]
> Dear @peadams,
> 
> no idea if this is of any help but we were able to get a working bonito (despite the wheel-installation problem) by using conda to install an environment containing python (3.8.6), pip (20.3), pytorch (1.5.0), cudatoolkit (10.2.89) and others; after activating this environment we installed bonito via pip (ignoring the wheel installation error):
> 
> ```
> conda create -n bonito python pip pytorch=1.5.0 torchvision cudatoolkit 'numpy<=1.18.5' -c pytorch -c conda-forge
> 
> conda activate bonito
> pip install ont-bonito
> ```
> 
> Now we are able to successfully basecall (on a system having GPUs installed) using
> 
> ```
> conda activate bonito
> bonito basecaller --device cuda ...
> ```

I followed similar procedure:
conda create  python pip pytorch=1.5.0 torchvision cudatoolkit 'numpy<=1.18.5' -c pytorch -c conda-forge --prefix /idle/envs/bonito
then I have installed one by one the requirements.txt by using pip
at the end I installed ont-bonito but I got similar error:

Building wheels for collected packages: ont-bonito
  Building wheel for ont-bonito (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /idle/ric.cirillo/envs/bonito/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v5zxhgro/ont-bonito_c86403d1347146a09ed5dc8b0f55a6c3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v5zxhgro/ont-bonito_c86403d1347146a09ed5dc8b0f55a6c3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-97wn1412
       cwd: /tmp/pip-install-v5zxhgro/ont-bonito_c86403d1347146a09ed5dc8b0f55a6c3/
  Complete output (93 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/bonito
  copying bonito/nn.py -> build/lib/bonito
  copying bonito/fast5.py -> build/lib/bonito
  copying bonito/__init__.py -> build/lib/bonito
  copying bonito/multiprocessing.py -> build/lib/bonito
  copying bonito/training.py -> build/lib/bonito
  copying bonito/aligner.py -> build/lib/bonito
  copying bonito/io.py -> build/lib/bonito
  copying bonito/util.py -> build/lib/bonito
  creating build/lib/bonito/crf
  copying bonito/crf/basecall.py -> build/lib/bonito/crf
  copying bonito/crf/__init__.py -> build/lib/bonito/crf
copying bonito/crf/model.py -> build/lib/bonito/crf
  creating build/lib/bonito/ctc
  copying bonito/ctc/basecall.py -> build/lib/bonito/ctc
  copying bonito/ctc/__init__.py -> build/lib/bonito/ctc
  copying bonito/ctc/model.py -> build/lib/bonito/ctc
  creating build/lib/bonito/cli
  copying bonito/cli/basecaller.py -> build/lib/bonito/cli
  copying bonito/cli/pair.py -> build/lib/bonito/cli
  copying bonito/cli/tune.py -> build/lib/bonito/cli
  copying bonito/cli/convert.py -> build/lib/bonito/cli
  copying bonito/cli/view.py -> build/lib/bonito/cli
  copying bonito/cli/train.py -> build/lib/bonito/cli
  copying bonito/cli/download.py -> build/lib/bonito/cli
  copying bonito/cli/__init__.py -> build/lib/bonito/cli
  copying bonito/cli/evaluate.py -> build/lib/bonito/cli
  running egg_info
  writing ont_bonito.egg-info/PKG-INFO
 writing dependency_links to ont_bonito.egg-info/dependency_links.txt
  writing entry points to ont_bonito.egg-info/entry_points.txt
  writing requirements to ont_bonito.egg-info/requires.txt
  writing top-level names to ont_bonito.egg-info/top_level.txt
  reading manifest file 'ont_bonito.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'ont_bonito.egg-info/SOURCES.txt'
  creating build/lib/bonito/data
  copying bonito/data/README.md -> build/lib/bonito/data
  creating build/lib/bonito/models
  copying bonito/models/README.md -> build/lib/bonito/models
  creating build/lib/bonito/models/configs
  copying bonito/models/configs/dna_r9.4.1@v1.toml -> build/lib/bonito/models/configs
  copying bonito/models/configs/dna_r9.4.1@v2.toml -> build/lib/bonito/models/configs
  copying bonito/models/configs/dna_r9.4.1@v3.toml -> build/lib/bonito/models/configs
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/bonito
 copying build/lib/bonito/nn.py -> build/bdist.linux-x86_64/wheel/bonito
  creating build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/crf/basecall.py -> build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/crf/__init__.py -> build/bdist.linux-x86_64/wheel/bonito/crf
  copying build/lib/bonito/crf/model.py -> build/bdist.linux-x86_64/wheel/bonito/crf
  creating build/bdist.linux-x86_64/wheel/bonito/ctc
  copying build/lib/bonito/ctc/basecall.py -> build/bdist.linux-x86_64/wheel/bonito/ctc
  copying build/lib/bonito/ctc/__init__.py -> build/bdist.linux-x86_64/wheel/bonito/ctc
  copying build/lib/bonito/ctc/model.py -> build/bdist.linux-x86_64/wheel/bonito/ctc
  creating build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/basecaller.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/pair.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/tune.py -> build/bdist.linux-x86_64/wheel/bonito/cli
copying build/lib/bonito/cli/convert.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/view.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/train.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/download.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/__init__.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/cli/evaluate.py -> build/bdist.linux-x86_64/wheel/bonito/cli
  copying build/lib/bonito/fast5.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/__init__.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/multiprocessing.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/training.py -> build/bdist.linux-x86_64/wheel/bonito
  copying build/lib/bonito/aligner.py -> build/bdist.linux-x86_64/wheel/bonito
  creating build/bdist.linux-x86_64/wheel/bonito/data
  copying build/lib/bonito/data/README.md -> build/bdist.linux-x86_64/wheel/bonito/data
  copying build/lib/bonito/io.py -> build/bdist.linux-x86_64/wheel/bonito
  creating build/bdist.linux-x86_64/wheel/bonito/models
  copying build/lib/bonito/models/README.md -> build/bdist.linux-x86_64/wheel/bonito/models
  creating build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/configs/dna_r9.4.1@v3.toml -> build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/configs/dna_r9.4.1@v1.toml -> build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/models/configs/dna_r9.4.1@v2.toml -> build/bdist.linux-x86_64/wheel/bonito/models/configs
  copying build/lib/bonito/util.py -> build/bdist.linux-x86_64/wheel/bonito
  running install_egg_info
  Copying ont_bonito.egg-info to build/bdist.linux-x86_64/wheel/ont_bonito-0.3.6-py3.8.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'bonito'
  ----------------------------------------
  ERROR: Failed building wheel for ont-bonito
  Running setup.py clean for ont-bonito
Failed to build ont-bonito
Installing collected packages: ont-bonito
    Running setup.py install for ont-bonito ... done
  DEPRECATION: ont-bonito was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed ont-bonito-0.3.6

and indeed bonito is running on my gpu Tesla V100-SXM2
 NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     

Can I be sure that bonito is properly working?? do you have dataset to check it?
Best

**Comment by iiSeymour** [comment]
@aspitaleri here is some testdata - https://nanoporetech.box.com/shared/static/0892js62z2otykfiii2mu7flep8t3dam.zip

```bash 
(bonito) /tmp$ wget -q --show-progress https://nanoporetech.box.com/shared/static/0892js62z2otykfiii2mu7flep8t3dam.zip  
(bonito) /tmp$ unzip 0892js62z2otykfiii2mu7flep8t3dam.zip 
(bonito) /tmp$ bonito evaluate dna_r9.4.1 --directory testdata/
* loading data
* loading model 0
* calling
* mean      97.21%
* median    97.85%
* time      3.15
* samples/s 1.52E+06
```

**Comment by aspitaleri** [comment]
Hi,
I tested and this what I get at the end:
alignment = parasail.sw_trace_striped_32(seq, ref, 8, 4, parasail.dnafull)
AttributeError: module 'parasail' has no attribute 'sw_trace_striped_32'

On my fast5 files using basecaller worked fine producing a fasta file as output. Do the npy file represents fast5 files?
thanks

**Comment by huangnengCSU** [comment]
@peadams 
I have the same problem, and it is due to that CUPY is inconsistent with the CUDA version. I reinstalled the module ```cupy``` then the problem is solved. [CUPY Installation](https://github.com/cupy/cupy)

**Comment by pbuendia** [comment]
I can't install bonito and used the above by @hermannschwaerzlerUIBK :
